import { Product, Category } from "./types";

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Crystals", slug: "crystals", description: "Raw and polished healing crystals", created_at: "2024-01-01" },
  { id: "cat-2", name: "Gemstones", slug: "gemstones", description: "Premium cut and polished gemstones", created_at: "2024-01-01" },
  { id: "cat-3", name: "Jewelry", slug: "jewelry", description: "Handcrafted crystal and gemstone jewelry", created_at: "2024-01-01" },
  { id: "cat-4", name: "Specimens", slug: "specimens", description: "Museum-quality mineral specimens", created_at: "2024-01-01" },
];

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Amethyst Cathedral Cluster",
    slug: "amethyst-cathedral-cluster",
    description: "A stunning deep-purple amethyst cathedral cluster from Uruguay. This specimen features brilliant crystal terminations with rich violet color that catches light beautifully. Each piece is unique — a true statement piece for any collection.",
    price: 189.99,
    compare_at_price: 249.99,
    category_id: "cat-1",
    category_slug: "crystals",
    images: ["/placeholder-crystal-1.jpg"],
    stock: 3,
    featured: true,
    active: true,
    properties: { weight: "2.4 kg", origin: "Uruguay", chakra: "Crown, Third Eye", hardness: "7" },
    created_at: "2024-01-15",
    updated_at: "2024-01-15",
  },
  {
    id: "prod-2",
    name: "Rose Quartz Sphere",
    slug: "rose-quartz-sphere",
    description: "Hand-polished rose quartz sphere radiating soft pink energy. Known as the stone of universal love, this sphere is perfect for meditation or as a calming presence in your space. Sourced from Madagascar.",
    price: 64.99,
    category_id: "cat-1",
    category_slug: "crystals",
    images: ["/placeholder-crystal-2.jpg"],
    stock: 8,
    featured: true,
    active: true,
    properties: { weight: "680g", origin: "Madagascar", chakra: "Heart", hardness: "7", dimensions: "3.5\" diameter" },
    created_at: "2024-01-16",
    updated_at: "2024-01-16",
  },
  {
    id: "prod-3",
    name: "Citrine Point Tower",
    slug: "citrine-point-tower",
    description: "Natural citrine point tower with warm golden hues. Citrine is known as the merchant's stone — believed to attract abundance and prosperity. This tower has been polished to reveal its inner fire.",
    price: 42.99,
    category_id: "cat-1",
    category_slug: "crystals",
    images: ["/placeholder-crystal-3.jpg"],
    stock: 12,
    featured: false,
    active: true,
    properties: { weight: "340g", origin: "Brazil", chakra: "Solar Plexus", hardness: "7", dimensions: "6\" tall" },
    created_at: "2024-01-17",
    updated_at: "2024-01-17",
  },
  {
    id: "prod-4",
    name: "Labradorite Free Form",
    slug: "labradorite-free-form",
    description: "Mesmerizing labradorite free-form piece with intense blue and gold flash. Labradorite is a stone of transformation and magic, revealing hidden colors when light strikes its surface at the right angle.",
    price: 79.99,
    category_id: "cat-2",
    category_slug: "gemstones",
    images: ["/placeholder-gem-1.jpg"],
    stock: 5,
    featured: true,
    active: true,
    properties: { weight: "520g", origin: "Madagascar", chakra: "Throat, Third Eye", hardness: "6-6.5" },
    created_at: "2024-01-18",
    updated_at: "2024-01-18",
  },
  {
    id: "prod-5",
    name: "Black Tourmaline Raw Chunk",
    slug: "black-tourmaline-raw-chunk",
    description: "Large raw black tourmaline chunk — the ultimate protection stone. Known for shielding against negative energy and electromagnetic fields. This substantial piece has a powerful grounding presence.",
    price: 34.99,
    category_id: "cat-1",
    category_slug: "crystals",
    images: ["/placeholder-crystal-4.jpg"],
    stock: 15,
    featured: false,
    active: true,
    properties: { weight: "890g", origin: "Brazil", chakra: "Root", hardness: "7-7.5" },
    created_at: "2024-01-19",
    updated_at: "2024-01-19",
  },
  {
    id: "prod-6",
    name: "Amethyst Wire-Wrapped Pendant",
    slug: "amethyst-wire-wrapped-pendant",
    description: "Handcrafted wire-wrapped amethyst pendant on sterling silver chain. Each pendant features a carefully selected amethyst point wrapped in intricate silver wirework. No two are exactly alike.",
    price: 54.99,
    category_id: "cat-3",
    category_slug: "jewelry",
    images: ["/placeholder-jewelry-1.jpg"],
    stock: 7,
    featured: true,
    active: true,
    properties: { weight: "18g", origin: "Brazil", chakra: "Crown, Third Eye" },
    created_at: "2024-01-20",
    updated_at: "2024-01-20",
  },
  {
    id: "prod-7",
    name: "Fluorite Octahedron Set",
    slug: "fluorite-octahedron-set",
    description: "Set of 5 natural fluorite octahedrons in varying colors — green, purple, blue, and clear. These naturally occurring geometric formations are a collector's dream. Comes in a velvet-lined display box.",
    price: 44.99,
    category_id: "cat-4",
    category_slug: "specimens",
    images: ["/placeholder-specimen-1.jpg"],
    stock: 4,
    featured: false,
    active: true,
    properties: { weight: "120g total", origin: "China", chakra: "Heart, Third Eye", hardness: "4" },
    created_at: "2024-01-21",
    updated_at: "2024-01-21",
  },
  {
    id: "prod-8",
    name: "Pyrite Cube Cluster",
    slug: "pyrite-cube-cluster",
    description: "Natural pyrite cube cluster from Spain — also known as fool's gold. These perfectly geometric cubes formed naturally over millions of years. An incredible conversation piece and a must for any mineral collection.",
    price: 119.99,
    category_id: "cat-4",
    category_slug: "specimens",
    images: ["/placeholder-specimen-2.jpg"],
    stock: 2,
    featured: true,
    active: true,
    properties: { weight: "1.1 kg", origin: "Navajún, Spain", chakra: "Solar Plexus", hardness: "6-6.5", dimensions: "4\" x 3\" x 3\"" },
    created_at: "2024-01-22",
    updated_at: "2024-01-22",
  },
];
